# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_searchepsgcrs.ui'
#
# Created: Sat Dec  6 16:24:04 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SearchEPSGCRS_dock(object):
    def setupUi(self, SearchEPSGCRS_dock):
        SearchEPSGCRS_dock.setObjectName(_fromUtf8("SearchEPSGCRS_dock"))
        SearchEPSGCRS_dock.resize(320, 702)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SearchEPSGCRS_dock.sizePolicy().hasHeightForWidth())
        SearchEPSGCRS_dock.setSizePolicy(sizePolicy)
        SearchEPSGCRS_dock.setMinimumSize(QtCore.QSize(320, 282))
        SearchEPSGCRS_dock.setMaximumSize(QtCore.QSize(350, 524287))
        self.dockWidgetContents = QtGui.QWidget()
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        self.dockWidgetContents.setFont(font)
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.txtCRS = QtGui.QLineEdit(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtCRS.sizePolicy().hasHeightForWidth())
        self.txtCRS.setSizePolicy(sizePolicy)
        self.txtCRS.setMinimumSize(QtCore.QSize(50, 30))
        self.txtCRS.setMaximumSize(QtCore.QSize(300, 30))
        self.txtCRS.setMaxLength(10)
        self.txtCRS.setAlignment(QtCore.Qt.AlignCenter)
        self.txtCRS.setObjectName(_fromUtf8("txtCRS"))
        self.verticalLayout.addWidget(self.txtCRS)
        self.getEPSGActiveLayerButton = QtGui.QPushButton(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.getEPSGActiveLayerButton.sizePolicy().hasHeightForWidth())
        self.getEPSGActiveLayerButton.setSizePolicy(sizePolicy)
        self.getEPSGActiveLayerButton.setMinimumSize(QtCore.QSize(270, 30))
        self.getEPSGActiveLayerButton.setMaximumSize(QtCore.QSize(300, 30))
        self.getEPSGActiveLayerButton.setObjectName(_fromUtf8("getEPSGActiveLayerButton"))
        self.verticalLayout.addWidget(self.getEPSGActiveLayerButton)
        self.tabWidget = QtGui.QTabWidget(self.dockWidgetContents)
        self.tabWidget.setMinimumSize(QtCore.QSize(300, 50))
        self.tabWidget.setMaximumSize(QtCore.QSize(320, 800))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab1 = QtGui.QWidget()
        self.tab1.setObjectName(_fromUtf8("tab1"))
        self.gridLayout = QtGui.QGridLayout(self.tab1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.tab1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(150, 30))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.txtResults1 = QtGui.QTextBrowser(self.tab1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtResults1.sizePolicy().hasHeightForWidth())
        self.txtResults1.setSizePolicy(sizePolicy)
        self.txtResults1.setMinimumSize(QtCore.QSize(270, 50))
        self.txtResults1.setMaximumSize(QtCore.QSize(320, 1000))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txtResults1.setFont(font)
        self.txtResults1.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.txtResults1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.txtResults1.setFrameShadow(QtGui.QFrame.Sunken)
        self.txtResults1.setLineWidth(1)
        self.txtResults1.setAcceptRichText(True)
        self.txtResults1.setObjectName(_fromUtf8("txtResults1"))
        self.gridLayout.addWidget(self.txtResults1, 4, 0, 1, 2)
        self.comboCRS = QtGui.QComboBox(self.tab1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboCRS.sizePolicy().hasHeightForWidth())
        self.comboCRS.setSizePolicy(sizePolicy)
        self.comboCRS.setMinimumSize(QtCore.QSize(100, 30))
        self.comboCRS.setMaximumSize(QtCore.QSize(130, 30))
        self.comboCRS.setObjectName(_fromUtf8("comboCRS"))
        self.comboCRS.addItem(_fromUtf8(""))
        self.comboCRS.addItem(_fromUtf8(""))
        self.comboCRS.addItem(_fromUtf8(""))
        self.comboCRS.addItem(_fromUtf8(""))
        self.comboCRS.addItem(_fromUtf8(""))
        self.comboCRS.addItem(_fromUtf8(""))
        self.comboCRS.addItem(_fromUtf8(""))
        self.comboCRS.addItem(_fromUtf8(""))
        self.comboCRS.addItem(_fromUtf8(""))
        self.comboCRS.addItem(_fromUtf8(""))
        self.comboCRS.addItem(_fromUtf8(""))
        self.comboCRS.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboCRS, 0, 2, 1, 1)
        self.FormattedCRSButton = QtGui.QPushButton(self.tab1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FormattedCRSButton.sizePolicy().hasHeightForWidth())
        self.FormattedCRSButton.setSizePolicy(sizePolicy)
        self.FormattedCRSButton.setMinimumSize(QtCore.QSize(270, 30))
        self.FormattedCRSButton.setMaximumSize(QtCore.QSize(300, 30))
        self.FormattedCRSButton.setObjectName(_fromUtf8("FormattedCRSButton"))
        self.gridLayout.addWidget(self.FormattedCRSButton, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tab1, _fromUtf8(""))
        self.tab2 = QtGui.QWidget()
        self.tab2.setObjectName(_fromUtf8("tab2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.transfCRSButton = QtGui.QPushButton(self.tab2)
        self.transfCRSButton.setMinimumSize(QtCore.QSize(270, 30))
        self.transfCRSButton.setMaximumSize(QtCore.QSize(270, 30))
        self.transfCRSButton.setObjectName(_fromUtf8("transfCRSButton"))
        self.gridLayout_3.addWidget(self.transfCRSButton, 0, 0, 1, 1)
        self.txtResults2 = QtGui.QTextBrowser(self.tab2)
        self.txtResults2.setMinimumSize(QtCore.QSize(270, 50))
        self.txtResults2.setMaximumSize(QtCore.QSize(320, 1000))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        self.txtResults2.setFont(font)
        self.txtResults2.setObjectName(_fromUtf8("txtResults2"))
        self.gridLayout_3.addWidget(self.txtResults2, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab2, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.aboutButton = QtGui.QPushButton(self.dockWidgetContents)
        self.aboutButton.setMinimumSize(QtCore.QSize(270, 30))
        self.aboutButton.setMaximumSize(QtCore.QSize(320, 30))
        self.aboutButton.setObjectName(_fromUtf8("aboutButton"))
        self.gridLayout_2.addWidget(self.aboutButton, 0, 0, 1, 1)
        self.helpButton = QtGui.QPushButton(self.dockWidgetContents)
        self.helpButton.setMinimumSize(QtCore.QSize(270, 0))
        self.helpButton.setMaximumSize(QtCore.QSize(320, 30))
        self.helpButton.setObjectName(_fromUtf8("helpButton"))
        self.gridLayout_2.addWidget(self.helpButton, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        SearchEPSGCRS_dock.setWidget(self.dockWidgetContents)

        self.retranslateUi(SearchEPSGCRS_dock)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SearchEPSGCRS_dock)

    def retranslateUi(self, SearchEPSGCRS_dock):
        SearchEPSGCRS_dock.setWindowTitle(_translate("SearchEPSGCRS_dock", "Search and format EPSG CRS Plugin", None))
        self.label.setText(_translate("SearchEPSGCRS_dock", "Type EPSG CRS code:", None))
        self.txtCRS.setToolTip(_translate("SearchEPSGCRS_dock", "<html><head/><body><p>Type EPSG code or push button &quot;Get active layer...&quot;. </p></body></html>", None))
        self.txtCRS.setText(_translate("SearchEPSGCRS_dock", "25830", None))
        self.getEPSGActiveLayerButton.setText(_translate("SearchEPSGCRS_dock", "Get active layer EPSG CRS code", None))
        self.label_2.setText(_translate("SearchEPSGCRS_dock", "Select output format:", None))
        self.txtResults1.setHtml(_translate("SearchEPSGCRS_dock", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Courier New\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.comboCRS.setItemText(0, _translate("SearchEPSGCRS_dock", ".prettywkt", None))
        self.comboCRS.setItemText(1, _translate("SearchEPSGCRS_dock", ".wkt", None))
        self.comboCRS.setItemText(2, _translate("SearchEPSGCRS_dock", ".esriwkt", None))
        self.comboCRS.setItemText(3, _translate("SearchEPSGCRS_dock", ".gml", None))
        self.comboCRS.setItemText(4, _translate("SearchEPSGCRS_dock", ".xml", None))
        self.comboCRS.setItemText(5, _translate("SearchEPSGCRS_dock", ".proj4", None))
        self.comboCRS.setItemText(6, _translate("SearchEPSGCRS_dock", ".js", None))
        self.comboCRS.setItemText(7, _translate("SearchEPSGCRS_dock", ".geoserver", None))
        self.comboCRS.setItemText(8, _translate("SearchEPSGCRS_dock", ".mapfile", None))
        self.comboCRS.setItemText(9, _translate("SearchEPSGCRS_dock", ".mapnik", None))
        self.comboCRS.setItemText(10, _translate("SearchEPSGCRS_dock", ".mapnikpython", None))
        self.comboCRS.setItemText(11, _translate("SearchEPSGCRS_dock", ".sql", None))
        self.FormattedCRSButton.setText(_translate("SearchEPSGCRS_dock", "GET FORMATTED CRS", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("SearchEPSGCRS_dock", "Formatted CRS", None))
        self.transfCRSButton.setText(_translate("SearchEPSGCRS_dock", "GET CRS TRANSFORMATIONS", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("SearchEPSGCRS_dock", "Transformations Info", None))
        self.aboutButton.setText(_translate("SearchEPSGCRS_dock", "About this plugin", None))
        self.helpButton.setText(_translate("SearchEPSGCRS_dock", "Help", None))

